### ISSUE TITLE
prediction-modelSummary sql references model_developement column which is not in the results table

### ISSUE THREAD

**Issue by egillax** [OHDSI/OhdsiShinyModules#23]
[Here](https://github.com/OHDSI/OhdsiShinyModules/blob/main/R/prediction-modelSummary.R#L180)  there is a reference in the SQL to a column ```model_development``` which doesn't exist causing the shiny app to error.

If I remove the condition ```model_development = 1``` from the sql the bug goes away and I can view my results.

**Comment by jreps** [comment]
You'll need to update PLP.  I had to add in the column otherwise the validations were over writing the development results if validated in the same database.

I need to made a few other changes to the result database which will mean changing the PLP and OhdsiShinyModels today as I need to make it such that some shared tables (cohort and database) can be used from other packages but also so that PLP can run by itself.  So, in a day you'll need to update both PLP and OhdsiShinyModules if updating one or the other.

**Comment by egillax** [comment]
yeah I see it now. Thought I had checked with the newest PLP develop but apparently not :) closing
