### ISSUE TITLE
Cohort Attrition Issue

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/OhdsiShinyModules#300]
On Cohorts --> Inclusion Rules & Attrition, there seems to be a an issue with the attrition reporting.

For "Treatment Resistant Depression" (16976), here are the attrition results for a single DB:
![image](https://github.com/OHDSI/Strategus/assets/6305439/dc7493a6-a7d1-4c00-96a5-e6b43febc9aa)

However this is how they are reported in Strategus:

![image](https://github.com/OHDSI/Strategus/assets/6305439/b1351c52-302f-4da0-a0b0-7af8509849a4)

It looks like the inclusion rule text got out of sync with the results.  For example, the "No prior mania" in Strategus seems to align with the final results found in Atlas.

Generated with OhdsiShinyModules v2.1.5.9000 and ShinyAppBuilder v2.0.1.9000

**Comment by anthonysena** [comment]
Moving to OhdsiShinyModules since this appears to be an issue at that level. If, for some reason, this is a bug with CohortGenerator or Strategus we can relocate this issue.

**Comment by nhall6** [comment]
tagging @chrisknoll because we worked on coding this together long ago

Chris - we wrote this function in an attempt to use the "bit" logic to get the attrition stats correct for the funnel plot. Our initial attempt is here: 

[https://github.com/OHDSI/OhdsiShinyModules/blob/815d0c8b44c96e359a6183a2f9bf94211c2166f8/R/cohort-generator-main.R#L842-L895](url)

Perhaps there is a simple typo or error somewhere?

**Comment by nhall6** [comment]
@ericaVoss this is now fixed in https://github.com/OHDSI/OhdsiShinyModules/pull/329

Thanks to @chrisknoll for all the help in solving this issue.
